create or replace function private.is_activity_member(activity_uuid uuid) returns boolean language sql stable security definer set search_path = '' as $$ select exists (select 1 from public.activity_members m where m.activity_id = $1 and m.user_id = (select auth.uid())); $$;
create or replace function private.is_activity_creator(activity_uuid uuid) returns boolean language sql stable security definer set search_path = '' as $$ select exists (select 1 from public.activities a where a.id = $1 and a.created_by = (select auth.uid())); $$;
revoke all on schema private from public;
revoke all on function private.is_activity_member(uuid), private.is_activity_creator(uuid) from public, anon, authenticated;
grant execute on function private.is_activity_member(uuid), private.is_activity_creator(uuid) to authenticated;
alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.activity_members enable row level security;
alter table public.ledger_units enable row level security;
alter table public.participants enable row level security;
alter table public.participant_claims enable row level security;
create policy profiles_select on public.profiles for select to authenticated using (true);
create policy profiles_update_self on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy activities_select_member on public.activities for select to authenticated using (private.is_activity_member(id));
create policy activities_update_creator on public.activities for update to authenticated using (private.is_activity_creator(id)) with check (private.is_activity_creator(id));
create policy members_select_member on public.activity_members for select to authenticated using (private.is_activity_member(activity_id));
create policy units_select_member on public.ledger_units for select to authenticated using (private.is_activity_member(activity_id));
create policy units_insert_creator on public.ledger_units for insert to authenticated with check (private.is_activity_creator(activity_id));
create policy units_update_creator on public.ledger_units for update to authenticated using (private.is_activity_creator(activity_id)) with check (private.is_activity_creator(activity_id));
create policy participants_select_member on public.participants for select to authenticated using (private.is_activity_member(activity_id));
create policy participants_insert_creator on public.participants for insert to authenticated with check (private.is_activity_creator(activity_id));
create policy participants_update_creator on public.participants for update to authenticated using (private.is_activity_creator(activity_id)) with check (private.is_activity_creator(activity_id));
create policy claims_select_member on public.participant_claims for select to authenticated using (private.is_activity_member(activity_id));
create policy claims_insert_self on public.participant_claims for insert to authenticated with check ((select auth.uid()) = user_id and private.is_activity_member(activity_id));
create policy claims_delete_self on public.participant_claims for delete to authenticated using ((select auth.uid()) = user_id);

grant select on public.profiles, public.activities, public.activity_members, public.ledger_units, public.participants, public.participant_claims to authenticated;
grant update (display_name, avatar_url) on public.profiles to authenticated;
grant update on public.activities, public.ledger_units, public.participants to authenticated;
grant insert on public.ledger_units, public.participants, public.participant_claims to authenticated;
grant delete on public.participant_claims to authenticated;
revoke all on public.profiles, public.activities, public.activity_members, public.ledger_units, public.participants, public.participant_claims from anon;
revoke execute on function public.set_updated_at() from public, anon, authenticated;
